/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface BctAuthorBlock {
        "avatar": string;
        "name": string;
        "text": string;
        "url": string;
    }
    interface BctSocials {
        "facebook": string;
        "instagram": string;
        "twitter": string;
        "youtube": string;
    }
}
declare global {
    interface HTMLBctAuthorBlockElement extends Components.BctAuthorBlock, HTMLStencilElement {
    }
    var HTMLBctAuthorBlockElement: {
        prototype: HTMLBctAuthorBlockElement;
        new (): HTMLBctAuthorBlockElement;
    };
    interface HTMLBctSocialsElement extends Components.BctSocials, HTMLStencilElement {
    }
    var HTMLBctSocialsElement: {
        prototype: HTMLBctSocialsElement;
        new (): HTMLBctSocialsElement;
    };
    interface HTMLElementTagNameMap {
        "bct-author-block": HTMLBctAuthorBlockElement;
        "bct-socials": HTMLBctSocialsElement;
    }
}
declare namespace LocalJSX {
    interface BctAuthorBlock {
        "avatar"?: string;
        "name"?: string;
        "text"?: string;
        "url"?: string;
    }
    interface BctSocials {
        "facebook"?: string;
        "instagram"?: string;
        "twitter"?: string;
        "youtube"?: string;
    }
    interface IntrinsicElements {
        "bct-author-block": BctAuthorBlock;
        "bct-socials": BctSocials;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "bct-author-block": LocalJSX.BctAuthorBlock & JSXBase.HTMLAttributes<HTMLBctAuthorBlockElement>;
            "bct-socials": LocalJSX.BctSocials & JSXBase.HTMLAttributes<HTMLBctSocialsElement>;
        }
    }
}
